- hosts: localhost
  gather_facts: no
  tasks:
    - name: Install necessary packages using apt
      become: yes
      apt:
        name:
          - pkg-config
          - libmysqlclient-dev
          - jq  # Add jq to the apt package list
        update_cache: yes

    - name: Install pip
      become: yes
      apt:
        name: python-pip  # Install pip using apt

    - name: Install jq using pip
      become: yes
      pip:
        name: jq  # Install jq using pip

    - name: Update pip to the latest version
      become: yes
      pip:
        name: pip
        state: latest

